// import { Index } from './index';
import Head from "next/head";
import React from "react";
import Land  from "./land";
import  Pictures  from "./pictures";
import axios from "axios";
import { useRouter } from "next/router";

export default function Index({ data }: any) {
  const router = useRouter();
  const { slug } = router.query;

  // console.log(slug)

  // console.log(data)
  // const name = data.sorted;
  const shoot = data.theName;
  const shootAll = data.theNameAll;

  // console.log(shootAll);

  return (
    <>
      <Head>
        <title>Services</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      services go here
      <Land data={shoot} />
      {/* <article id="article">
        WE PPROMISE RESPECT
        <h2> Mechanical and Civil Constuction</h2>
        <ul>
          <li>Steel fabrication and construction</li>
          <li>Mechanical construction and pipes installation</li>
          <li>
            Erection of steel structure - We do Steel welding, Stainless,
            Aluminum, Copper and plastic
          </li>
          <li>
            We weld Structures, pipelines, tanks, pressure vessels and boilers
          </li>
        </ul>
      </article> */}
      <Pictures data={shoot} dataAll={shootAll} />
      <aside>
        Our Other Services
        <ul>
          <li>Mechanical and Civil Constrution</li>
          <li>Water Treatment</li>
          <li>
            Supply, Services, Repair and Installation of Workshop Machines
          </li>
          <li>Road Construction</li>
          <li>HVAC Services</li>
          <li>Workshop Equipment Supply</li>
          <li>Agricultural Engineering</li>
          <li>Electrical Engineering</li>
          <li>Renewable Energy</li>
          <li>PAC Housing</li>
          <li>Barricades</li>
          {/* <li></li> */}
        </ul>
      </aside>
    </>
  );
}

export async function getServerSideProps(context: any) {
  // console.log(serviceResponse.data);
  const { params } = context;
  const slugId = params.slug;

  const x = await axios.post("http://localhost:3000/api/postTest", {
    slug: slugId,
  });

  // const serviceResponse = await axios.get("http://localhost:3000/api/postTest");

  // console.log(serviceResponse)
  return {
    props: {
      data: x.data,
    },
  };
}
